name: Run script from Pastebin

on:
  push:
    branches:
      - main

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download script from Pastebin
      run: |
        curl -o my_script.py https://pastebin.com/raw/PmuufTuM  # Remplace par l'URL de ton script Pastebin

    - name: Run script
      run: |
        python3 my_script.py
