name: Keep Replit Alive  

on:  
  workflow_dispatch: 
  schedule:  
    - cron: "*/5 * * * *"  # Exécute toutes les 5 minutes  

jobs:  
  ping:  
    runs-on: ubuntu-latest  
    steps:  
      - name: Envoyer une requête à Replit  
        run: curl -I https://3bd89d87-2e9a-4eb4-b243-cb5cefb72965-00-1ngl3lnf2pymn.spock.replit.dev/
